Feat/login
Creath-Tech/liga_independente_frontend pull request #4
Opened 2024-05-06 15:05 UTC by Av3z

Implementei uma nova feature de login, desenvolvendo a estrutura para garantir uma organização eficiente e modular do código.

**Criação da Estrutura:** Desenvolvi uma estrutura completa para a feature de login, estabelecendo uma arquitetura limpa e bem organizada desde o início.

**Service Layer:** Implementei uma camada de serviço dedicada para gerenciar as operações de login, promovendo uma separação clara das responsabilidades e facilitando futuras expansões.

**Utilização de Dados Mockados:** Integrei dados mockados para simplificar o desenvolvimento e teste da funcionalidade de login 
durante o ciclo de desenvolvimento inicial.

2024-05-06 17:36 UTC, raposo8 approved these changes
O código está limpo e bem componentizado.

2024-05-06 20:36 UTC, acacioejunior requested changes
Comentei alguns ajustes no codigo.

2024-05-06 20:36 UTC, acacioejunior commented on lib/src/pages/login_page.dart
O Arquivo login_page.dart não tem uma controller e esta usando diretamente um Service que seria a Model. Sugestão é criar uma login_controller.dart, que nessa implementação vai só chamar a Model auth_service.

2024-05-06 20:36 UTC, acacioejunior commented on lib/src/pages/login_page.dart
> +  final TextEditingController loginEC = TextEditingController();
linhas 14,15,16 estão com o conteudo da controller. migrar para o arquivo login_controller.dart

2024-05-06 20:36 UTC, acacioejunior commented on lib/src/pages/login_page.dart
> +  void signIn() async {
Metodo da Controller.

2024-05-06 20:36 UTC, acacioejunior commented on lib/src/app.dart
Para melhorar as organização dos arquivos pode ser usado pastas para agrupar Features. 

Ex:
lib/src
           login/
                     login_page.dart
                     login_controller.dart
                     widgets/
                                    custom_input.dart
                                    primary_button.dart

2024-05-07 19:28 UTC, Av3z commented on lib/src/pages/login_page.dart
> +  void signIn() async {
Controller implementada.

2024-05-07 19:28 UTC, Av3z commented on lib/src/app.dart
Ok, vamos passar para a equipe, onde será realizada a documentação da arquitetura.

2024-05-07 23:05 UTC, acacioejunior approved these changes

2024-05-07 23:06 UTC, merged