teste appium
Creath-Tech/liga_independente_frontend pull request #5
Opened 2024-05-07 23:19 UTC by alemao1305

Teste de automação Appium, com android studio

2024-05-09 02:57 UTC, Av3z submitted a review, later dismissed
Ficou muito boa a documentação, principalmente a parte sobre os desligamento do **VULKAN** e uso do vídeo integrado.

2024-05-09 18:52 UTC, acacioejunior requested changes
Favor manter o conteudo antigo e adicionar a parte do Appium

2024-05-09 18:52 UTC, acacioejunior commented on README.md
> -# 🛠️ Ambiente de desenvolvimento
Não podemos remover a documentação do Ambiente de Desenvolvimento.

2024-05-09 19:54 UTC, alemao1305 commented on README.md
> -# 🛠️ Ambiente de desenvolvimento
Boa tarde, acabei de corrigir e coloquei a documentação do appium no final antes do feed back, vou subir o readme corrigido

2024-05-13 02:14 UTC, acacioejunior approved these changes

2024-05-13 02:19 UTC, merged