firebase configuration
Creath-Tech/liga_independente_frontend pull request #6
Opened 2024-05-08 20:11 UTC by Av3z

Implementada configuração inicial do Firebase, limitada aos ambientes iOS e Android.

2024-05-08 20:26 UTC, acacioejunior requested changes
Ajustar o package Android.

2024-05-08 20:26 UTC, acacioejunior commented on android/app/google-services.json
> +          "package_name": "com.example.liga_independente_frontend"
O Package Android está como example. Utiliza algo parecido com o iOS.

iOS no Arquivo GoogleService-info.plist está assim: com.creath.ligaapp.ligaIndependenteFrontend

2024-05-09 02:36 UTC, Av3z commented on android/app/google-services.json
> +          "package_name": "com.example.liga_independente_frontend"
Fiz a alteração do package name para com.creath.ligaapp.ligaIndependenteFrontend

2024-05-09 18:38 UTC, acacioejunior approved these changes

2024-05-09 18:40 UTC, merged